# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPUImageMy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GPUImageMy

  target 'GPUImageMyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GPUImageMyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'GPUImage', '~> 0.1.7'
pod 'Masonry', '~> 1.0.2'
end
